### ISSUE TITLE
[Bug]: Empty dialog boxes

### ISSUE THREAD

**Issue by furiousg4m3r** [lifebottle/Narikiri-Dungeon-X#19]
### Version details

v0.0.3

### How do you play the game?

Hardware

### Contact Details

FuriousG4m3r

### Where in the game the bug is occuring?

ETHOS’ HOUSE

### Description of the issue

During the tutorial there is no explanation text in the dialog box. 
![2022-11-02-195418](https://user-images.githubusercontent.com/77897370/199626263-d03b51e4-6be5-4642-8c29-10470d191f16.png)

**Comment by fortiersteven** [comment]
@furiousg4m3r Do you think you can paste here the original japanese text or a screenshot, it would be helpful for us to find the issue, good job on finding the bug!

**Comment by fortiersteven** [comment]
Ok, I think I got it @furiousg4m3r 
![image](https://user-images.githubusercontent.com/74146408/199978861-8276360d-4545-4d3d-83c5-92125689a25a.png)

**Comment by fortiersteven** [comment]
@Fis-Ura Do you think you can help me find this text?
It doesn't seem to be inside the Story or Event files :/
Is it part of BT_DATA?

**Comment by fortiersteven** [comment]
@Fis-Ura Ok, Im pretty sure its from the file ep_010_040, text was extracted in XML but it doesnt seem to be reinserted properly. Maybe because the entry doesn't have a VoiceId
![image](https://user-images.githubusercontent.com/74146408/199983559-6e6d8b7f-ae6b-4273-8db0-0e8464db0ad4.png)

**Comment by fortiersteven** [comment]
hey @furiousg4m3r  and @Fis-Ura Can you tell me if you still have this issue with this new patch
[NDX_patch_0.0.4.zip](https://github.com/lifebottle/Narikiri-Dungeon-X/files/9943951/NDX_patch_0.0.4.zip)

**Comment by furiousg4m3r** [comment]
Still blank for me also some of the name tags are coming back as "Error".

**Comment by fortiersteven** [comment]
@furiousg4m3r Oh, I know what you mean, hmm, let me check it again
![image](https://user-images.githubusercontent.com/74146408/200174911-7b30b58f-9d33-4c9e-a184-4f9278a10cfd.png)

**Comment by fortiersteven** [comment]
@furiousg4m3r 
I got a new patch that should be good now, sorry about that :)
[NDX_patch_0.0.4.zip](https://github.com/lifebottle/Narikiri-Dungeon-X/files/9946028/NDX_patch_0.0.4.zip)

**Comment by furiousg4m3r** [comment]
@fortiersteven "Error" names are fixed. Also the tutorial has text again, albeit untranslated but a step in the right direction. 
![2022-11-06-211547](https://user-images.githubusercontent.com/77897370/200213708-0b282e66-a458-4d20-a3e4-1f574536b4e0.png)

**Comment by furiousg4m3r** [comment]
Also found another tutorial in 0.0.4 without text a little further in. At the tower.
![2022-11-07-092005](https://user-images.githubusercontent.com/77897370/200366744-d0a62c75-7730-4639-af92-6c6dc59a2c43.png)

**Comment by furiousg4m3r** [comment]
That second tutorial has text in the 0.0.4 test release.

**Comment by fortiersteven** [comment]
Closing it for now
